### ISSUE TITLE
ring v0.16.15 compiling failed in x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by marvinpan8** [briansmith/ring#1034]
**ring v0.16.15 compiling failed in x86_64-pc-windows-gnu, can you help me?
The output detail as below:**
```bash
D:/../cargo-cache/bin/cargo.exe build --color=always --all --all-targets
   Compiling ring v0.16.15
   Compiling pin-project v0.4.22
   Compiling mio v0.6.22
   Compiling mime_guess v2.0.3
   Compiling chrono v0.4.13
   Compiling hmac v0.7.1
   Compiling pbkdf2 v0.3.0
   Compiling serde v1.0.114
error: failed to run custom build command for `ring v0.16.15`

Caused by:
  process didn't exit successfully: `D:\code\jrtzcloud\rust\quotes-bak-task\target\debug\build\ring-660116a2c32db87e\build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

--- stderr
ENV =::=::\
ENV =C:=C:\
ENV =E:=E:\
ENV ALLUSERSPROFILE=C:\ProgramData
ENV APPDATA=C:\Users\lenovo\AppData\Roaming
ENV CARGO=\\?\D:\rust-toolchain\toolchains\stable-x86_64-pc-windows-gnu\bin\cargo.exe
ENV CARGO_CFG_TARGET_ARCH=x86_64
ENV CARGO_CFG_TARGET_ENDIAN=little
ENV CARGO_CFG_TARGET_ENV=gnu
ENV CARGO_CFG_TARGET_FAMILY=windows
ENV CARGO_CFG_TARGET_FEATURE=fxsr,sse,sse2
ENV CARGO_CFG_TARGET_OS=windows
ENV CARGO_CFG_TARGET_POINTER_WIDTH=64
ENV CARGO_CFG_TARGET_VENDOR=pc
ENV CARGO_CFG_WINDOWS=
ENV CARGO_FEATURE_ALLOC=1
ENV CARGO_FEATURE_DEFAULT=1
ENV CARGO_FEATURE_DEV_URANDOM_FALLBACK=1
ENV CARGO_FEATURE_ONCE_CELL=1
ENV CARGO_HOME=D:\cargo-cache
ENV CARGO_MAKEFLAGS=--jobserver-fds=__rust_jobserver_semaphore_3852140781 --jobserver-auth=__rust_jobserver_semaphore_3852140781
ENV CARGO_MANIFEST_DIR=D:\cargo-cache\registry\src\192.168.14.111-3280b4d813d8e5e7\ring-0.16.15
ENV CARGO_MANIFEST_LINKS=ring-asm
ENV CARGO_PKG_AUTHORS=Brian Smith <brian@briansmith.org>
ENV CARGO_PKG_DESCRIPTION=Safe, fast, small crypto using Rust.
ENV CARGO_PKG_HOMEPAGE=
ENV CARGO_PKG_NAME=ring
ENV CARGO_PKG_REPOSITORY=https://github.com/briansmith/ring
ENV CARGO_PKG_VERSION=0.16.15
ENV CARGO_PKG_VERSION_MAJOR=0
ENV CARGO_PKG_VERSION_MINOR=16
ENV CARGO_PKG_VERSION_PATCH=15
ENV CARGO_PKG_VERSION_PRE=
ENV COMMONPROGRAMFILES=C:\Program Files\Common Files
ENV COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
ENV COMMONPROGRAMW6432=C:\Program Files\Common Files
ENV COMPUTERNAME=NB74
ENV COMSPEC=C:\Windows\system32\cmd.exe
ENV CONFIGSETROOT=C:\Windows\ConfigSetRoot
ENV DEBUG=true
ENV DRIVERDATA=C:\Windows\System32\Drivers\DriverData
ENV FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
ENV FPS_BROWSER_USER_PROFILE_STRING=Default
ENV HOMEDRIVE=C:
ENV HOMEPATH=\Users\lenovo
ENV HOST=x86_64-pc-windows-gnu
ENV IDEA_INITIAL_DIRECTORY=D:\dev\CLion-2020.1.1\jbr\bin
ENV LD_LIBRARY_PATH=D:\rust-toolchain\toolchains\stable-x86_64-pc-windows-gnu\lib
ENV LOCALAPPDATA=C:\Users\lenovo\AppData\Local
ENV LOGONSERVER=\\NB74
ENV NLS_LANG=SIMPLIFIED CHINESE_CHINA.AL32UTF8
ENV NUMBER_OF_PROCESSORS=8
ENV NUM_JOBS=8
ENV OPENSSL_CONF=D:\dev\OpenSSL-Win64\bin\openssl.cfg
ENV OPT_LEVEL=0
ENV OS=Windows_NT
ENV OUT_DIR=D:\code\jrtzcloud\rust\quotes-bak-task\target\debug\build\ring-4f1f9af66122bee2\out
ENV PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
ENV PROCESSOR_ARCHITECTURE=AMD64
ENV PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
ENV PROCESSOR_LEVEL=6
ENV PROCESSOR_REVISION=8e0a
ENV PROFILE=debug
ENV PROGRAMDATA=C:\ProgramData
ENV PROGRAMFILES=C:\Program Files
ENV PROGRAMFILES(X86)=C:\Program Files (x86)
ENV PROGRAMW6432=C:\Program Files
ENV PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
ENV PUBLIC=C:\Users\Public
ENV RUSTC=rustc
ENV RUSTDOC=rustdoc
ENV RUSTUP_HOME=D:\rust-toolchain
ENV RUSTUP_TOOLCHAIN=stable-x86_64-pc-windows-gnu
ENV RUST_BACKTRACE=short
ENV RUST_RECURSION_COUNT=1
ENV SESSIONNAME=Console
ENV SYSTEMDRIVE=C:
ENV SYSTEMROOT=C:\Windows
ENV TARGET=x86_64-pc-windows-gnu
ENV TEMP=C:\Users\lenovo\AppData\Local\Temp
ENV TERM=ansi
ENV TMP=C:\Users\lenovo\AppData\Local\Temp
ENV USERDOMAIN=NB74
ENV USERDOMAIN_ROAMINGPROFILE=NB74
ENV USERNAME=lenovo
ENV USERPROFILE=C:\Users\lenovo
ENV VS190COMNTOOLS=D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\

running "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oD:\\code\\jrtzcloud\\rust\\quotes-bak-task\\target\\debug\\build\\ring-4f1f9af66122bee2\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
thread 'main' panicked at 'failed to execute ["gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oD:\\code\\jrtzcloud\\rust\\quotes-bak-task\\target\\debug\\build\\ring-4f1f9af66122bee2\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"]: 系统找不到指定的文件。 (os error 2)', D:\cargo-cache\registry\src\192.168.14.111-3280b4d813d8e5e7\ring-0.16.15\build.rs:661:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:470
  11: rust_begin_unwind
             at src\libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:332
  13: build_script_build::run_command::{{closure}}
             at .\build.rs:661
  14: core::result::Result<T,E>::unwrap_or_else
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore/result.rs:851
  15: build_script_build::run_command
             at .\build.rs:660
  16: build_script_build::compile
             at .\build.rs:532
  17: build_script_build::build_library::{{closure}}
             at .\build.rs:467
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\ops/function.rs:285
  19: core::option::Option<T>::map
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore/option.rs:456
  20: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\adapters/mod.rs:791
  21: alloc::vec::Vec<T>::extend_desugared
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc/vec.rs:2138
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc/vec.rs:2031
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc/vec.rs:2026
  24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc/vec.rs:1926
  25: core::iter::traits::iterator::Iterator::collect
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\traits/iterator.rs:1659
  26: build_script_build::build_library
             at .\build.rs:463
  27: build_script_build::build_c_code::{{closure}}
             at .\build.rs:436
  28: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\traits/iterator.rs:655
  29: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\traits/iterator.rs:2001
  30: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\traits/iterator.rs:1877
  31: core::iter::traits::iterator::Iterator::fold
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\traits/iterator.rs:2004
  32: core::iter::traits::iterator::Iterator::for_each
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\iter\traits/iterator.rs:658
  33: build_script_build::build_c_code
             at .\build.rs:435
  34: build_script_build::ring_build_rs_main
             at .\build.rs:298
  35: build_script_build::main
             at .\build.rs:255
  36: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd/rt.rs:67
  37: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  38: std::panicking::try::do_call
             at src\libstd/panicking.rs:303
  39: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:86
  40: std::panicking::try
             at src\libstd/panicking.rs:281
  41: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  42: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  43: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd/rt.rs:67
  44: main
  45: __tmainCRTStartup
             at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:335
  46: mainCRTStartup
             at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:219
  47: unit_addrs_search
  48: unit_addrs_search
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by marvinpan8** [comment]
When building from Git for Windows, directories containing yasm.exe and perl.exe must be in %PATH%, where yasm.exe is Yasm 1.3 or later and where perl.exe is recommended to be Strawberry Perl.

**Comment by briansmith** [comment]
> When building from Git for Windows, directories containing yasm.exe and perl.exe must be in %PATH%, where yasm.exe is Yasm 1.3 or later and where perl.exe is recommended to be Strawberry Perl.

I don't think that is the issue you were running. If you are using a release of *ring* from crates.io then neither yasm nor perl is required. They are only required if you are building a custom build of *ring*.

**Comment by briansmith** [comment]
> "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oD:\\code\\jrtzcloud\\rust\\quotes-bak-task\\target\\debug\\build\\ring-4f1f9af66122bee2\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"

That's the command that fails. What happens if you run that command manually from the command line?

**Comment by briansmith** [comment]
Also, what version of GCC are you using? What's the output of `gcc --version`?

**Comment by Kungitoo** [comment]
@marvinpan8 did adding those 2 to your path fix the issue? I'm having the exact same problem

**Comment by briansmith** [comment]
I will attempt to add some CI/CD to verify that *ring* works correctly on x86_64-pc-windows-gnu. I believe most people are using the -msvc target for Windows and I've never tried the -gnu target. I recommend people use the -msvc target when practical.

**Comment by briansmith** [comment]
In PR #1087 I added the x86_64-pc-windows-gnu target to the (new) GitHub Actions matrix and everything worked. Further, in https://github.com/briansmith/webpki/pull/143 I added the same target to webpki's build matrix, which verifies that the latest version on crates.io (0.16.5) works on x86_64-pc-windows-gnu ; see https://github.com/briansmith/webpki/runs/1383483441?check_suite_focus=true for an example.
