### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Grommish** [briansmith/ring#1484]
I'm throwing the following when attempting to build [vaultwarden](https://github.com/dani-garcia/vaultwarden).

Would you be able to tell me where to look?  I have no idea if it's a `ring` issue or if it's just being invoked incorrectly by `vaultwarden`.

Rust Host Tuple: `x86_64-unknown-linux-gnu`
Rust Target Tuple: `mips64-openwrt-linux-musl`

```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/grommish/openwrt/build_dir/target-mips64_octeonplus_64_musl/vaultwarden-1.22.2/target/release/build/ring-942b806af6091f53/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/grommish/openwrt/staging_dir/host/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  stack backtrace:
     0:     0x5610bf905d8c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ed9448498ca38f3
     1:     0x5610bf92148e - core::fmt::write::h6a9df48ba6802568
     2:     0x5610bf8ebc41 - std::io::Write::write_fmt::h89207bdb546d01b9
     3:     0x5610bf8f3226 - std::panicking::default_hook::{{closure}}::h341862156c048848
     4:     0x5610bf8f2ebc - std::panicking::default_hook::h07a8a2b45bf4a7ce
     5:     0x5610bf8f3859 - std::panicking::rust_panic_with_hook::hac8ad8c31042550f
     6:     0x5610bf9061e9 - std::panicking::begin_panic_handler::{{closure}}::h2fe5717231b04092
     7:     0x5610bf905eb4 - std::sys_common::backtrace::__rust_end_short_backtrace::hccc267d86a176f94
     8:     0x5610bf8f3362 - rust_begin_unwind
     9:     0x5610bf874953 - core::panicking::panic_fmt::hb10233d1bb668f2d
    10:     0x5610bf87481d - core::panicking::panic::h34f9dfd369b5aa95
    11:     0x5610bf87fd2e - core::option::Option<T>::unwrap::he57649cc5eb572a2
    12:     0x5610bf879435 - build_script_build::build_c_code::h3d427e98e2a7d0d1
    13:     0x5610bf878961 - build_script_build::ring_build_rs_main::h61d70adaa6d19c21
    14:     0x5610bf87820a - build_script_build::main::ha5cc8fa76a24f955
    15:     0x5610bf888f33 - core::ops::function::FnOnce::call_once::h741973736787c600
    16:     0x5610bf87f979 - std::sys_common::backtrace::__rust_begin_short_backtrace::h570ac5d4aedc2624
    17:     0x5610bf888d99 - std::rt::lang_start::{{closure}}::h94e5fe27a0b3e7ed
    18:     0x5610bf8e68b1 - std::rt::lang_start_internal::h9f307c43cc49ec67
    19:     0x5610bf888d81 - std::rt::lang_start::h5cbdda27b11fc6f6
    20:     0x5610bf87e763 - main
    21:     0x7fa838a220b3 - __libc_start_main
    22:     0x5610bf8750be - _start
    23:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Grommish** [comment]
More `ring` issues:

```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/nym-1.0.4/target/release/build/ring-22fbac0ffbcec208/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /media/data/openwrt/staging_dir/host/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  stack backtrace:
     0:     0x55784284cd6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ed9448498ca38f3
     1:     0x55784286855e - core::fmt::write::h6a9df48ba6802568
     2:     0x557842832a51 - std::io::Write::write_fmt::h89207bdb546d01b9
     3:     0x55784283a046 - std::panicking::default_hook::{{closure}}::h341862156c048848
     4:     0x557842839cdc - std::panicking::default_hook::h07a8a2b45bf4a7ce
     5:     0x55784283a679 - std::panicking::rust_panic_with_hook::hac8ad8c31042550f
     6:     0x55784284d1c9 - std::panicking::begin_panic_handler::{{closure}}::h2fe5717231b04092
     7:     0x55784284ce94 - std::sys_common::backtrace::__rust_end_short_backtrace::hccc267d86a176f94
     8:     0x55784283a182 - rust_begin_unwind
     9:     0x5578427ae953 - core::panicking::panic_fmt::hb10233d1bb668f2d
    10:     0x5578427ae81d - core::panicking::panic::h34f9dfd369b5aa95
    11:     0x5578427b9e2e - core::option::Option<T>::unwrap::h94e3f6e2d2e24521
    12:     0x5578427b3455 - build_script_build::build_c_code::h0b0756ddd493940e
    13:     0x5578427b297c - build_script_build::ring_build_rs_main::h20f8c55cc8313880
    14:     0x5578427b220a - build_script_build::main::h369604830e443f41
    15:     0x5578427c2f93 - core::ops::function::FnOnce::call_once::h0e15f67ba3009ee1
    16:     0x5578427b9b39 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb2ba33cef2384846
    17:     0x5578427baf79 - std::rt::lang_start::{{closure}}::h373541d3a8a55da0
    18:     0x55784282d6c1 - std::rt::lang_start_internal::h9f307c43cc49ec67
    19:     0x5578427baf61 - std::rt::lang_start::h1f673febc58b91c4
    20:     0x5578427b87c3 - main
    21:     0x7f8c3134a0b3 - __libc_start_main
    22:     0x5578427af0be - _start
    23:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
make[2]: *** [Makefile:54: /media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/nym-1.0.4/.built] Error 101
```

Invoked with the following:
```
RUSTFLAGS="-C linker=/media/data/openwrt/staging_dir/toolchain-mips64_octeonplus_64_gcc-11.2.0_musl/bin/mips64-openwrt-linux-musl-gcc -C ar=/media/data/openwrt/staging_dir/toolchain-mips64_octeonplus_64_gcc-11.2.0_musl/bin/mips64-openwrt-linux-musl-gcc-ar -C target-cpu=octeon+" CARGO_HOME="/media/data/openwrt/staging_dir/host" TARGET_CC=/media/data/openwrt/staging_dir/toolchain-mips64_octeonplus_64_gcc-11.2.0_musl/bin/mips64-openwrt-linux-musl-gcc TARGET_AR=/media/data/openwrt/staging_dir/toolchain-mips64_octeonplus_64_gcc-11.2.0_musl/bin/mips64-openwrt-linux-musl-gcc-ar RUST_BACKTRACE=full cargo build -v --release -Z build-std --target mips64-openwrt-linux-musl
```

**Comment by Grommish** [comment]
When building `ring` from the repo.

```
     Running `/media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/ring-0.12.1/target/release/build/ring-859c10ef1be73549/build-script-build`
error: failed to run custom build command for `ring v0.17.0-not-released-yet (/media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/ring-0.12.1)`

Caused by:
  process didn't exit successfully: `/media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/ring-0.12.1/target/release/build/ring-859c10ef1be73549/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_0_not_released_yet_
  OPT_LEVEL = Some("3")
  TARGET = Some("mips64-openwrt-linux-musl")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_mips64-openwrt-linux-musl = None
  CC_mips64_openwrt_linux_musl = None
  TARGET_CC = Some("/media/data/openwrt/staging_dir/toolchain-mips64_octeonplus_64_gcc-11.2.0_musl/bin/mips64-openwrt-linux-musl-gcc")
  CFLAGS_mips64-openwrt-linux-musl = None
  CFLAGS_mips64_openwrt_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = Some("")
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fp64,llvm14-builtins-abi")

  --- stderr
  running "/media/data/openwrt/staging_dir/toolchain-mips64_octeonplus_64_gcc-11.2.0_musl/bin/mips64-openwrt-linux-musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "include" "-I" "/media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/ring-0.12.1/target/mips64-openwrt-linux-musl/release/build/ring-7e00d6b704218c01/out" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/media/data/openwrt/build_dir/target-mips64_octeonplus_64_musl/ring-0.12.1/target/mips64-openwrt-linux-musl/release/build/ring-7e00d6b704218c01/out/curve25519.o" "crypto/curve25519/curve25519.c"
  In file included from include/ring-core/mem.h:60,
                   from crypto/curve25519/curve25519.c:22:
  include/ring-core/base.h:99:2: error: #error "Unknown target CPU"
     99 | #error "Unknown target CPU"
        |  ^~~~~
  In file included from crypto/curve25519/internal.h:20,
                   from crypto/curve25519/curve25519.c:24:
  crypto/curve25519/../internal.h:178:2: error: #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
    178 | #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
        |  ^~~~~
  crypto/curve25519/../internal.h:191:15: error: unknown type name 'crypto_word'
    191 | static inline crypto_word value_barrier_w(crypto_word a) {
        |               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:191:43: error: unknown type name 'crypto_word'
    191 | static inline crypto_word value_barrier_w(crypto_word a) {
        |                                           ^~~~~~~~~~~
  crypto/curve25519/../internal.h:216:15: error: unknown type name 'crypto_word'
    216 | static inline crypto_word constant_time_msb_w(crypto_word a) {
        |               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:216:47: error: unknown type name 'crypto_word'
    216 | static inline crypto_word constant_time_msb_w(crypto_word a) {
        |                                               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:221:15: error: unknown type name 'crypto_word'
    221 | static inline crypto_word constant_time_is_zero_w(crypto_word a) {
        |               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:221:51: error: unknown type name 'crypto_word'
    221 | static inline crypto_word constant_time_is_zero_w(crypto_word a) {
        |                                                   ^~~~~~~~~~~
  crypto/curve25519/../internal.h:236:15: error: unknown type name 'crypto_word'
    236 | static inline crypto_word constant_time_is_nonzero_w(crypto_word a) {
        |               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:236:54: error: unknown type name 'crypto_word'
    236 | static inline crypto_word constant_time_is_nonzero_w(crypto_word a) {
        |                                                      ^~~~~~~~~~~
  crypto/curve25519/../internal.h:241:15: error: unknown type name 'crypto_word'
    241 | static inline crypto_word constant_time_eq_w(crypto_word a,
        |               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:241:46: error: unknown type name 'crypto_word'
    241 | static inline crypto_word constant_time_eq_w(crypto_word a,
        |                                              ^~~~~~~~~~~
  crypto/curve25519/../internal.h:242:48: error: unknown type name 'crypto_word'
    242 |                                                crypto_word b) {
        |                                                ^~~~~~~~~~~
  crypto/curve25519/../internal.h:249:15: error: unknown type name 'crypto_word'
    249 | static inline crypto_word constant_time_select_w(crypto_word mask,
        |               ^~~~~~~~~~~
  crypto/curve25519/../internal.h:249:50: error: unknown type name 'crypto_word'
    249 | static inline crypto_word constant_time_select_w(crypto_word mask,
        |                                                  ^~~~~~~~~~~
  crypto/curve25519/../internal.h:250:52: error: unknown type name 'crypto_word'
    250 |                                                    crypto_word a,
        |                                                    ^~~~~~~~~~~
  crypto/curve25519/../internal.h:251:52: error: unknown type name 'crypto_word'
    251 |                                                    crypto_word b) {
        |                                                    ^~~~~~~~~~~
  thread 'main' panicked at 'execution failed', build.rs:707:9
  stack backtrace:
     0:     0x560d352a3a4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ed9448498ca38f3
     1:     0x560d352bfa7e - core::fmt::write::h6a9df48ba6802568
     2:     0x560d35289921 - std::io::Write::write_fmt::h89207bdb546d01b9
     3:     0x560d35290f06 - std::panicking::default_hook::{{closure}}::h341862156c048848
     4:     0x560d35290b9c - std::panicking::default_hook::h07a8a2b45bf4a7ce
     5:     0x560d35291539 - std::panicking::rust_panic_with_hook::hac8ad8c31042550f
     6:     0x560d35266458 - std::panicking::begin_panic::{{closure}}::hf09a4e9d90a9b194
     7:     0x560d3526b346 - std::sys_common::backtrace::__rust_end_short_backtrace::h5af3986253053161
     8:     0x560d352663c6 - std::panicking::begin_panic::h1aeb3bc23472301a
     9:     0x560d3521246d - build_script_build::run_command::h72d88ab86554e464
    10:     0x560d35210cd6 - build_script_build::compile::h54fa1b63a8562ca1
    11:     0x560d3521090d - build_script_build::build_library::{{closure}}::h0f4211fc8cbcdac0
    12:     0x560d35223dc4 - core::iter::adapters::map::map_fold::{{closure}}::h5d94d6820d72ad18
    13:     0x560d3521d3fa - core::iter::traits::iterator::Iterator::fold::heac003147a8a98a5
    14:     0x560d3521e8c2 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold::h755936f584f8be10
    15:     0x560d352244ff - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h5642ba4b87391512
    16:     0x560d3522489e - core::iter::traits::iterator::Iterator::for_each::h5819343ba0b1136d
    17:     0x560d35216ba7 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hb5deee444dfc648b
    18:     0x560d3521651e - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h75f414f4eb2e81d8
    19:     0x560d3521675c - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h7c64644f0190803a
    20:     0x560d3521773b - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h2a73d584bc12fadc
    21:     0x560d35224b4c - core::iter::traits::iterator::Iterator::collect::h614f1bc19d1763d3
    22:     0x560d35210270 - build_script_build::build_library::h80828f5249ac82f5
    23:     0x560d352100e7 - build_script_build::build_c_code::{{closure}}::h1c49cbaad8f2303d
    24:     0x560d3521df72 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::hc4dbf8223423157b
    25:     0x560d3520fd81 - build_script_build::build_c_code::h2d459cb8abc2afe9
    26:     0x560d3520eaa2 - build_script_build::ring_build_rs_main::h9b9680e7169315be
    27:     0x560d3520e39e - build_script_build::main::hd308d622556e8c04
    28:     0x560d35219873 - core::ops::function::FnOnce::call_once::h8429cb542b842623
    29:     0x560d3521c859 - std::sys_common::backtrace::__rust_begin_short_backtrace::h09899cd593bc119e
    30:     0x560d3521a5c9 - std::rt::lang_start::{{closure}}::h9113a53c96ae830e
    31:     0x560d35284591 - std::rt::lang_start_internal::h9f307c43cc49ec67
    32:     0x560d3521a5b1 - std::rt::lang_start::h5cd4cee1564f9b1a
    33:     0x560d352154a3 - main
    34:     0x7f61f6a3a0b3 - __libc_start_main
    35:     0x560d3520e0be - _start
    36:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

From HEAD `0f3bf0031a8dbba741b26f1f02ebde6b7db4a3d6`

**Comment by Grommish** [comment]
https://github.com/briansmith/ring/blob/main/include/ring-core/base.h#L95

Well, that solves that :D

**Comment by gyrusdentatus** [comment]
> https://github.com/briansmith/ring/blob/main/include/ring-core/base.h#L95
> 
> Well, that solves that :D

Any more...details on how this fixes it? How do I get rid of all `ring v0.16.20` from my dependency tree and use the latest master repo? I feel so dumb now after all this time trying  to make it work

**Comment by Grommish** [comment]
Bottom line, ring crate uses BoringSSL, which doesn't work on BigEndian
arches. If I'm building for LittleEndian arches, it's fine.

**Comment by gyrusdentatus** [comment]
@briansmith 
Hello Brian,

Would you have/know a solution for compiling _Ring_ for target _aarch64-unknown-musl_? 64-bit raspi running OpenWRT. I can compile with `cross` but not with `cargo` which makes it a bit of a trouble when trying to create a package for OpenWRT. 

I would be really really grateful for any advice/solution on this matter or even getting in touch over email if you have a 10 min to spare. It's for a greater good :)

**Comment by Grommish** [comment]
This isn't a `ring` issue.
