### ISSUE TITLE
Unable to build on aarch64

### ISSUE THREAD

**Issue by mickenordin** [briansmith/ring#1497]
Hi, when building on the pinephonepro I get this error:

```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/mobian/src/tubefeeder/src/Tubefeeder-1.6.6/target/release/build/ring-e602e52d481900e8/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-unknown-linux-gnu")
  HOST = Some("aarch64-unknown-linux-gnu")
  CC_aarch64-unknown-linux-gnu = None
  CC_aarch64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_aarch64-unknown-linux-gnu = None
  CFLAGS_aarch64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = Some("-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection")
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None

  --- stderr
  running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=x86-64" "-mtune=generic" "-O2" "-pipe" "-fno-plt" "-fexceptions" "-Wp,-D_FORTIFY_SOURCE=2" "-Wformat" "-Werror=format-security" "-fstack-clash-protection" "-fcf-protection" "-I" "include" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/mobian/src/tubefeeder/src/Tubefeeder-1.6.6/target/release/build/ring-ccfc52d9df21f3fa/out/aesv8-armx-linux64.o" "/home/mobian/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux64.S"
  cc1: error: unknown value ‘x86-64’ for ‘-march’
  cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-r native
  cc1: error: ‘-fcf-protection=full’ is not supported for this target
  Assembler messages:
  Error: unknown architecture `x86-64'

  Error: unrecognized option -march=x86-64
  thread 'main' panicked at 'execution failed', /home/mobian/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
  stack backtrace:
     0:     0xaaaac312c688 - std::backtrace_rs::backtrace::libunwind::trace::h129e00118d9f766e
                                 at /usr/src/rustc-1.58.1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0xaaaac312c688 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b6efba3d9d4c8d
                                 at /usr/src/rustc-1.58.1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0xaaaac312c688 - std::sys_common::backtrace::_print_fmt::he0eae45d1a016f50
                                 at /usr/src/rustc-1.58.1/library/std/src/sys_common/backtrace.rs:67:5
     3:     0xaaaac312c688 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc06868b45e2c4bb4
                                 at /usr/src/rustc-1.58.1/library/std/src/sys_common/backtrace.rs:46:22
     4:     0xaaaac3153bbc - core::fmt::write::hcdedbc05e38a6115
                                 at /usr/src/rustc-1.58.1/library/core/src/fmt/mod.rs:1149:17
     5:     0xaaaac31207e8 - std::io::Write::write_fmt::h06c74556923038e0
                                 at /usr/src/rustc-1.58.1/library/std/src/io/mod.rs:1697:15
     6:     0xaaaac3122b2c - std::sys_common::backtrace::_print::h05be5f3575c807ce
                                 at /usr/src/rustc-1.58.1/library/std/src/sys_common/backtrace.rs:49:5
     7:     0xaaaac3122b2c - std::sys_common::backtrace::print::he4fdcc4533b8f81a
                                 at /usr/src/rustc-1.58.1/library/std/src/sys_common/backtrace.rs:36:9
     8:     0xaaaac3122b2c - std::panicking::default_hook::{{closure}}::h3b8cca7a0570392b
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:211:50
     9:     0xaaaac31226b0 - std::panicking::default_hook::he1775adaac99ae80
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:228:9
    10:     0xaaaac3123094 - std::panicking::rust_panic_with_hook::h9838d954e44ff636
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:606:17
    11:     0xaaaac31076a4 - std::panicking::begin_panic::{{closure}}::hc475e1a13698ae48
    12:     0xaaaac3108c14 - std::sys_common::backtrace::__rust_end_short_backtrace::hc22253593bd6146c
    13:     0xaaaac3107604 - std::panicking::begin_panic::h16c30b87d1807425
    14:     0xaaaac30c1cb8 - build_script_build::run_command::hefb35c36250526bb
    15:     0xaaaac30c0dd8 - build_script_build::compile::hdb6c4b29dd9295d3
    16:     0xaaaac30c0a28 - build_script_build::build_library::{{closure}}::h0902fa92d6b61ded
    17:     0xaaaac30bebd4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hd71a9a818f1118b8
    18:     0xaaaac30c4750 - core::option::Option<T>::map::h86d0abe7964ac609
    19:     0xaaaac30c7d58 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h73d0282c86f68f57
    20:     0xaaaac30bc998 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h426a3093785ace3e
    21:     0xaaaac30be9e8 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::ha31c3a5b926325de
    22:     0xaaaac30be4a8 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h59254fe6d726dd19
    23:     0xaaaac30c8264 - core::iter::traits::iterator::Iterator::collect::h304c841a80ff6fbd
    24:     0xaaaac30c0430 - build_script_build::build_library::h4d3b93fb9fc8ad5d
    25:     0xaaaac30c0234 - build_script_build::build_c_code::{{closure}}::hc785c7456688dd79
    26:     0xaaaac30c7760 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::hf38f2484d4a4b14d
    27:     0xaaaac30bff60 - build_script_build::build_c_code::hb357383e956929c9
    28:     0xaaaac30bf2f4 - build_script_build::ring_build_rs_main::ha0f376a0536fe75c
    29:     0xaaaac30bed80 - build_script_build::main::hb8be7f1923118964
    30:     0xaaaac30cca9c - core::ops::function::FnOnce::call_once::h97dea20b209a057c
    31:     0xaaaac30c34d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb255864fd5ff5df1
    32:     0xaaaac30cc824 - std::rt::lang_start::{{closure}}::h4d5f1e280c4bf82d
    33:     0xaaaac311ee7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc7be548fe023abb1
                                 at /usr/src/rustc-1.58.1/library/core/src/ops/function.rs:259:13
    34:     0xaaaac311ee7c - std::panicking::try::do_call::he1bbc547dfe16af2
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:406:40
    35:     0xaaaac311ee7c - std::panicking::try::h16e067a9ec6d7888
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:370:19
    36:     0xaaaac311ee7c - std::panic::catch_unwind::h6bba0d79af97d0b8
                                 at /usr/src/rustc-1.58.1/library/std/src/panic.rs:133:14
    37:     0xaaaac311ee7c - std::rt::lang_start_internal::{{closure}}::h03c14055a7f6ce5d
                                 at /usr/src/rustc-1.58.1/library/std/src/rt.rs:128:48
    38:     0xaaaac311ee7c - std::panicking::try::do_call::h44dbafd4d68c4f63
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:406:40
    39:     0xaaaac311ee7c - std::panicking::try::h62036b9eb365e42e
                                 at /usr/src/rustc-1.58.1/library/std/src/panicking.rs:370:19
    40:     0xaaaac311ee7c - std::panic::catch_unwind::h3f0248700651f43b
                                 at /usr/src/rustc-1.58.1/library/std/src/panic.rs:133:14
    41:     0xaaaac311ee7c - std::rt::lang_start_internal::heff6f8e7e4ffb6dc
                                 at /usr/src/rustc-1.58.1/library/std/src/rt.rs:128:20
    42:     0xaaaac30cc800 - std::rt::lang_start::h0f5c02928f47173a
    43:     0xaaaac30c3484 - main
    44:     0xffffa9feb614 - __libc_start_main
    45:     0xaaaac30bc6b8 - _start
    46:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
[!] A failure occurred in build().
    Aborting...
```
I think the issue is caused by line 220 in build.rs:

```
("x86_64", None, Some("elf")),
```
My guess is that this will match anything, and anything below that will be unable to match. Removing the line worked for me, and maybe moving the line down below everything else in that section could work too if you want the catch all to be x86_64.

**Comment by olix0r** [comment]
You probably need set some of these environment variables:

https://github.com/briansmith/ring/blob/0f3bf0031a8dbba741b26f1f02ebde6b7db4a3d6/mk/cargo.sh#L50-L56

---

> I think the issue is caused by line 220 in build.rs:
>
> ```
> ("x86_64", None, Some("elf")),
> ```

For what it's worth, line 220 doesn't look like that on main: https://github.com/briansmith/ring/blob/0f3bf0031a8dbba741b26f1f02ebde6b7db4a3d6/build.rs#L220

**Comment by mickenordin** [comment]
It did not work to set any of those env variables, however it did work to run the build of the dependent project like this:

```
CFLAGS="" cargo build --frozen --release --all-features
```
