### ISSUE TITLE
Spaces in File Path Break Build.rs for target x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by KSBilodeau** [briansmith/ring#1502]
While attempting to cross compile my serenity project - which relies on ring - to x86_64-unknown-linux-gnu using zigbuild, I encountered a startling error that caused my build to fail, which goes as follows:

```rs
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/Users/ksbilodeau/Documents/Programming Projects/RustProjects/carl-bot/target/debug/build/ring-c8556b45bf7328fc/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = Some("/Users/ksbilodeau/Library/Caches/cargo-zigbuild/0.9.0/zigcc-x86_64-unknown-linux-gnu.sh")
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,llvm14-builtins-abi,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")

  --- stderr
  running "/Users/ksbilodeau/Library/Caches/cargo-zigbuild/0.9.0/zigcc-x86_64-unknown-linux-gnu.sh" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/Users/ksbilodeau/Documents/Programming Projects/RustProjects/carl-bot/target/x86_64-unknown-linux-gnu/debug/build/ring-b6c346889cf24df9/out/aesni-x86_64-elf.o" "/Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"
  ld.lld: error: cannot open Projects/RustProjects/carl-bot/target/x86_64-unknown-linux-gnu/debug/build/ring-b6c346889cf24df9/out/aesni-x86_64-elf.o: No such file or directory
  thread 'main' panicked at 'execution failed', /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
```

Please note the line `error: cannot open Projects/RustProjects/carl-bot/target/x86_64-unknown-linux-gnu/debug/build/ring-b6c346889cf24df9/out/aesni-x86_64-elf.o: No such file or directory`.  

As you can see towards the beginning of the error, the actually fully qualified path is `/Users/ksbilodeau/Documents/Programming Projects/RustProjects/carl-bot/target/x86_64-unknown-linux-gnu/debug/build/ring-b6c346889cf24df9/out/aesni-x86_64-elf.o`.

It appears at some point there is an improper split on space, which breaks users that have them in their paths when trying to compile for x86_64-unknown-linux-gnu.  This bug does not appear to affect native building on x86_64-apple-darwin, however.

Here is a full backtrace as per the usual for bug reports:

```rs
  stack backtrace:
     0:        0x10f692434 - std::backtrace_rs::backtrace::libunwind::trace::h4dbea4e5312094e8
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x10f692434 - std::backtrace_rs::backtrace::trace_unsynchronized::h7c1a105845b2dc6d
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x10f692434 - std::sys_common::backtrace::_print_fmt::h15e3b67fd84c4725
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:66:5
     3:        0x10f692434 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb12f2d2fb8fb2c88
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:45:22
     4:        0x10f6abcab - core::fmt::write::he7b9dfe274b3c137
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/fmt/mod.rs:1196:17
     5:        0x10f68e8d8 - std::io::Write::write_fmt::hfb7a67ad082fb8ed
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/io/mod.rs:1654:15
     6:        0x10f69437d - std::sys_common::backtrace::_print::hf60718a041a889c1
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:48:5
     7:        0x10f69437d - std::sys_common::backtrace::print::h01b334b2ac07f10b
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:35:9
     8:        0x10f69437d - std::panicking::default_hook::{{closure}}::h3567933f40f6c8ae
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:295:22
     9:        0x10f6940d4 - std::panicking::default_hook::hab9d06ed8714e431
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:314:9
    10:        0x10f6948a8 - std::panicking::rust_panic_with_hook::h6329d36721e7c523
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:698:17
    11:        0x10f63c08d - std::panicking::begin_panic::{{closure}}::h50136cfdae1878e2
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:617:9
    12:        0x10f65f4c8 - std::sys_common::backtrace::__rust_end_short_backtrace::hcc2df0b9950fb10f
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:138:18
    13:        0x10f6b1be1 - std::panicking::begin_panic::h5f713615731e995f
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:616:12
    14:        0x10f5fc08a - build_script_build::run_command::h714aef9c2f91c1dd
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
    15:        0x10f5facf7 - build_script_build::compile::h5aa963aa5194e62d
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:512:13
    16:        0x10f5fa782 - build_script_build::build_library::{{closure}}::h2db68dfda9d8e9dc
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:447:18
    17:        0x10f5f7ee0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h17599248422340fc
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:301:13
    18:        0x10f6001a3 - core::option::Option<T>::map::hb274ce250c65a82f
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/option.rs:929:29
    19:        0x10f60504d - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hb3e4a2ca3bbf33f9
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/iter/adapters/map.rs:103:9
    20:        0x10f5f5700 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::hfc3f9ef4570eac33
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
    21:        0x10f5f7d4b - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h7ac850491ac9d43d
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/alloc/src/vec/spec_from_iter.rs:33:9
    22:        0x10f5f758a - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::hce50607d0768c1c0
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/alloc/src/vec/mod.rs:2616:9
    23:        0x10f60570b - core::iter::traits::iterator::Iterator::collect::h2fe3379dd1b37662
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/iter/traits/iterator.rs:1792:9
    24:        0x10f5f9f62 - build_script_build::build_library::hde50171c004a63fe
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:443:16
    25:        0x10f5f9dd4 - build_script_build::build_c_code::{{closure}}::h5804db2061fb987e
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:416:9
    26:        0x10f60386a - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::h573343b72da5941e
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/slice/iter/macros.rs:211:21
    27:        0x10f5f99a8 - build_script_build::build_c_code::h8a9d8467bbe6841e
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:415:5
    28:        0x10f5f87b9 - build_script_build::ring_build_rs_main::h136e6794ebf587b7
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:279:5
    29:        0x10f5f80cf - build_script_build::main::he332b34bf5fcc29f
                                 at /Users/ksbilodeau/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:240:13
    30:        0x10f5fe2ce - core::ops::function::FnOnce::call_once::hf9f778cc2c7c187e
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
    31:        0x10f5fef41 - std::sys_common::backtrace::__rust_begin_short_backtrace::he44e83b20e234117
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:122:18
    32:        0x10f608804 - std::rt::lang_start::{{closure}}::h48ccd757303cb7b1
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/rt.rs:145:18
    33:        0x10f68a3be - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb618825e643232f3
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:280:13
    34:        0x10f68a3be - std::panicking::try::do_call::h047c4d38eff56e8e
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:492:40
    35:        0x10f68a3be - std::panicking::try::h5e6c9bfdb8cdbd2f
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:456:19
    36:        0x10f68a3be - std::panic::catch_unwind::h02ad5b7847b77928
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panic.rs:137:14
    37:        0x10f68a3be - std::rt::lang_start_internal::{{closure}}::heee6c7462fd8e4cb
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/rt.rs:128:48
    38:        0x10f68a3be - std::panicking::try::do_call::h237e2bdf34e6298e
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:492:40
    39:        0x10f68a3be - std::panicking::try::h8730c197a70da396
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:456:19
    40:        0x10f68a3be - std::panic::catch_unwind::h1f7b26ca6c5cbd9b
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panic.rs:137:14
    41:        0x10f68a3be - std::rt::lang_start_internal::hfe01e88909afac8e
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/rt.rs:128:20
    42:        0x10f6087de - std::rt::lang_start::h6a59f99e08901005
                                 at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/rt.rs:144:17
    43:        0x10f5fdf96 - _main
```

**Comment by briansmith** [comment]
Thanks. I am open to accepting a PR that fixes this.
