### ISSUE TITLE
Mac M1: cargo build fails with "error: index must be an integer in range [-256, 255]"

### ISSUE THREAD

**Issue by lynndylanhurley** [briansmith/ring#1521]
### Error:

```
error: failed to run custom build command for `ring v0.16.20`
...
  /var/folders/bg/y72tcmz14zj5xdp3qjjgq6wm0000gn/T//cc4hHtJy.s:2759:15: error: index must be an integer in range [-256, 255].
          ldr     x0, [x0, ___stack_chk_guard];momd
                           ^
  /var/folders/bg/y72tcmz14zj5xdp3qjjgq6wm0000gn/T//cc4hHtJy.s:2931:15: error: index must be an integer in range [-256, 255].
          ldr     x0, [x0, ___stack_chk_guard];momd
                           ^
  thread 'main' panicked at 'execution failed', /Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
...
```

I originally got this when trying to install `trunk`, but it also happens when this is the only dependency in my project:

```
# Cargo.toml
# ...

[dependencies]
ring = "0.16.20"
```

Trunk issue for reference:
https://github.com/thedodd/trunk/issues/444

<details>
  <summary>Full error</summary>

  ```
  Caused by:
    process didn't exit successfully: `/<omitted>target/debug/build/ring-07bc0e8cd1f784ad/build-script-build` (signal: 6, SIGABRT: process abort signal)
    --- stdout
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
    OPT_LEVEL = Some("0")
    TARGET = Some("aarch64-apple-darwin")
    HOST = Some("aarch64-apple-darwin")
    CC_aarch64-apple-darwin = None
    CC_aarch64_apple_darwin = None
    HOST_CC = None
    CC = None
    CFLAGS_aarch64-apple-darwin = None
    CFLAGS_aarch64_apple_darwin = None
    HOST_CFLAGS = None
    CFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  
    --- stderr
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/aesv8-armx-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/ghashv8-armx-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghashv8-armx-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/vpaes-armv8-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/vpaes-armv8-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/armv8-mont-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/armv8-mont-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/chacha-armv8-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/chacha-armv8-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/ecp_nistz256-armv8-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ecp_nistz256-armv8-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/ghash-neon-armv8-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghash-neon-armv8-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/sha512-armv8-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/sha512-armv8-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/sha256-armv8-ios64.o" "/Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/sha256-armv8-ios64.S"
    running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/lynn/Code/Graveflex/time-slayer/target/debug/build/ring-1f4f2f31a4704555/out/aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
    /var/folders/bg/y72tcmz14zj5xdp3qjjgq6wm0000gn/T//ccsziSEu.s:2759:15: error: index must be an integer in range [-256, 255].
            ldr     x0, [x0, ___stack_chk_guard];momd
                             ^
    /var/folders/bg/y72tcmz14zj5xdp3qjjgq6wm0000gn/T//ccsziSEu.s:2931:15: error: index must be an integer in range [-256, 255].
            ldr     x0, [x0, ___stack_chk_guard];momd
                             ^
    thread 'main' panicked at 'execution failed', /Users/lynn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    fatal runtime error: failed to initiate panic, error 5
  ```
</details>

Output of `rustup show`:

```
❯ rustup show                                   
Default host: aarch64-apple-darwin
rustup home:  /Users/lynn/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

Any ideas on how to work around this?

**Comment by tjni** [comment]
I don't know how to resolve this in your system, but the error signature looks like https://github.com/iains/gcc-darwin-arm64/issues/54.

**Comment by lynndylanhurley** [comment]
I think this was a result of some x86 libs still being referenced somehow. i nuked my homebrew folder that was still lingering from when i migrated to the M1 and was able to get past this issue.
