### ISSUE TITLE
Cross compilation from `x86_64-pc-windows-msvc` to `x86_64-unknown-linux-gnu` or `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by brian6932** [briansmith/ring#1712]
<details>
    <summary>gnu</summary>

```rust
❯ cargo build --target=x86_64-unknown-linux-gnu --release
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `...\target\release\build\ring-bb4671a4dab4b074\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

  --- stderr
  running "x86_64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o...\\target\\x86_64-unknown-linux-gnu\\release\\build\\ring-af4f1bd274e1f00d\\out\\aesni-x86_64-elf.o" "~\\scoop\\persist\\rustup-msvc\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\ring-0.16.20\\pregenerated\\aesni-x86_64-elf.S"
  thread 'main' panicked at ~\scoop\persist\rustup-msvc\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ring-0.16.20\build.rs:653:9:
  failed to execute ["x86_64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o...\\target\\x86_64-unknown-linux-gnu\\release\\build\\ring-af4f1bd274e1f00d\\out\\aesni-x86_64-elf.o" "~\\scoop\\persist\\rustup-msvc\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\ring-0.16.20\\pregenerated\\aesni-x86_64-elf.S"]: program not found
  stack backtrace:
     0:     0x7ff6a19693ed - <unknown>
     1:     0x7ff6a198556d - <unknown>
     2:     0x7ff6a1964691 - <unknown>
     3:     0x7ff6a19691da - <unknown>
     4:     0x7ff6a196bf19 - <unknown>
     5:     0x7ff6a196bbb8 - <unknown>
     6:     0x7ff6a196c458 - <unknown>
     7:     0x7ff6a196c32d - <unknown>
     8:     0x7ff6a196a1f9 - <unknown>
     9:     0x7ff6a196c010 - <unknown>
    10:     0x7ff6a198ae67 - <unknown>
    11:     0x7ff6a18c79dd - <unknown>
    12:     0x7ff6a18c1a49 - <unknown>
    13:     0x7ff6a18c78ae - <unknown>
    14:     0x7ff6a18c657c - <unknown>
    15:     0x7ff6a18c60d5 - <unknown>
    16:     0x7ff6a18c1850 - <unknown>
    17:     0x7ff6a18c99ce - <unknown>
    18:     0x7ff6a18d21d7 - <unknown>
    19:     0x7ff6a18d3d51 - <unknown>
    20:     0x7ff6a18d3b17 - <unknown>
    21:     0x7ff6a18cb231 - <unknown>
    22:     0x7ff6a18c58bd - <unknown>
    23:     0x7ff6a18c56d1 - <unknown>
    24:     0x7ff6a18d15d7 - <unknown>
    25:     0x7ff6a18c5067 - <unknown>
    26:     0x7ff6a18c3e86 - <unknown>
    27:     0x7ff6a18c38f2 - <unknown>
    28:     0x7ff6a18cd79b - <unknown>
    29:     0x7ff6a18ccf0e - <unknown>
    30:     0x7ff6a18ccf81 - <unknown>
    31:     0x7ff6a19605f8 - <unknown>
    32:     0x7ff6a18ccf5a - <unknown>
    33:     0x7ff6a18c9779 - <unknown>
    34:     0x7ff6a19898f0 - <unknown>
    35:     0x7fff7fea7344 - BaseThreadInitThunk
    36:     0x7fff808626b1 - RtlUserThreadStart
warning: build failed, waiting for other jobs to finish...
```
</details>

<details>
    <summary>musl</summary>

```rust
❯ cargo build --target=x86_64-unknown-linux-musl --release
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `...\target\release\build\ring-bb4671a4dab4b074\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-musl")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-musl
  CC_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_musl
  CC_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-musl
  CFLAGS_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_musl
  CFLAGS_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

  --- stderr
  running "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o...\\target\\x86_64-unknown-linux-musl\\release\\build\\ring-891c802267622083\\out\\aesni-x86_64-elf.o" "~\\scoop\\persist\\rustup-msvc\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\ring-0.16.20\\pregenerated\\aesni-x86_64-elf.S"
  thread 'main' panicked at ~\scoop\persist\rustup-msvc\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ring-0.16.20\build.rs:653:9:
  failed to execute ["musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o...\\target\\x86_64-unknown-linux-musl\\release\\build\\ring-891c802267622083\\out\\aesni-x86_64-elf.o" "~\\scoop\\persist\\rustup-msvc\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\ring-0.16.20\\pregenerated\\aesni-x86_64-elf.S"]: program not found
  stack backtrace:
     0:     0x7ff6a19693ed - <unknown>
     1:     0x7ff6a198556d - <unknown>
     2:     0x7ff6a1964691 - <unknown>
     3:     0x7ff6a19691da - <unknown>
     4:     0x7ff6a196bf19 - <unknown>
     5:     0x7ff6a196bbb8 - <unknown>
     6:     0x7ff6a196c458 - <unknown>
     7:     0x7ff6a196c32d - <unknown>
     8:     0x7ff6a196a1f9 - <unknown>
     9:     0x7ff6a196c010 - <unknown>
    10:     0x7ff6a198ae67 - <unknown>
    11:     0x7ff6a18c79dd - <unknown>
    12:     0x7ff6a18c1a49 - <unknown>
    13:     0x7ff6a18c78ae - <unknown>
    14:     0x7ff6a18c657c - <unknown>
    15:     0x7ff6a18c60d5 - <unknown>
    16:     0x7ff6a18c1850 - <unknown>
    17:     0x7ff6a18c99ce - <unknown>
    18:     0x7ff6a18d21d7 - <unknown>
    19:     0x7ff6a18d3d51 - <unknown>
    20:     0x7ff6a18d3b17 - <unknown>
    21:     0x7ff6a18cb231 - <unknown>
    22:     0x7ff6a18c58bd - <unknown>
    23:     0x7ff6a18c56d1 - <unknown>
    24:     0x7ff6a18d15d7 - <unknown>
    25:     0x7ff6a18c5067 - <unknown>
    26:     0x7ff6a18c3e86 - <unknown>
    27:     0x7ff6a18c38f2 - <unknown>
    28:     0x7ff6a18cd79b - <unknown>
    29:     0x7ff6a18ccf0e - <unknown>
    30:     0x7ff6a18ccf81 - <unknown>
    31:     0x7ff6a19605f8 - <unknown>
    32:     0x7ff6a18ccf5a - <unknown>
    33:     0x7ff6a18c9779 - <unknown>
    34:     0x7ff6a19898f0 - <unknown>
    35:     0x7fff7fea7344 - BaseThreadInitThunk
    36:     0x7fff808626b1 - RtlUserThreadStart
warning: build failed, waiting for other jobs to finish...
```
</details>

**Comment by briansmith** [comment]
https://github.com/briansmith/ring/blob/main/BUILDING.md#supported-toolchains-and-cross-compiling
