### ISSUE TITLE
Rust Embedded ESP32C6 STD (Does Ring support the target "riscv32imac-esp-espidf" ?)

### ISSUE THREAD

**Issue by blue-freedom-technologies** [briansmith/ring#1765]
Hello,

I think I am missing a rustflag that is preventing  the compiler to finish.  If not could someone point myself in the right direction ?

config.toml

```rust
[build]
target = "riscv32imac-esp-espidf"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c6"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.1"
ESP_IDF_SDKCONFIG = "sdkconfig.defaults"`
```

Error:
```text
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/silveira/bluefreedom/microcontroller/std/wifi-app/target/debug/build/ring-3c9642843c6b7cde/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/silveira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  stack backtrace:
     0:     0x55dac60e74ec - std::backtrace_rs::backtrace::libunwind::trace::h1fbf870cefe9105e
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55dac60e74ec - std::backtrace_rs::backtrace::trace_unsynchronized::h978b11b27e2f243b
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55dac60e74ec - std::sys_common::backtrace::_print_fmt::habb025370c831f53
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x55dac60e74ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h175d0c4e72d8b01b
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55dac610e6a0 - core::fmt::rt::Argument::fmt::h71591df08c361895
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/fmt/rt.rs:142:9
     5:     0x55dac610e6a0 - core::fmt::write::h878da2805c06feb0
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/fmt/mod.rs:1117:17
     6:     0x55dac60e43df - std::io::Write::write_fmt::hce996c3c2e33dbfb
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/io/mod.rs:1762:15
     7:     0x55dac60e72d4 - std::sys_common::backtrace::_print::h7b2452fe1769eb8d
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x55dac60e72d4 - std::sys_common::backtrace::print::hfa5833c6d1916a1a
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x55dac60e9107 - std::panicking::default_hook::{{closure}}::h44e0919432853577
    10:     0x55dac60e8e6f - std::panicking::default_hook::h93e4296aa60de0bc
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:292:9
    11:     0x55dac60e9588 - std::panicking::rust_panic_with_hook::hcdbdbaebb0a43fc3
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:731:13
    12:     0x55dac60e9439 - std::panicking::begin_panic_handler::{{closure}}::hf55fea61efc61efe
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:601:13
    13:     0x55dac60e79b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h4c571597a30d8d60
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/sys_common/backtrace.rs:170:18
    14:     0x55dac60e91d2 - rust_begin_unwind
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:597:5
    15:     0x55dac6046675 - core::panicking::panic_fmt::ha700422250cfa942
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/panicking.rs:72:14
    16:     0x55dac6046713 - core::panicking::panic::hb6a41ca25c8149c4
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/panicking.rs:127:5
    17:     0x55dac604a2e0 - core::option::Option<T>::unwrap::heda08372157f4253
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/option.rs:925:21
    18:     0x55dac604fb7c - build_script_build::build_c_code::hf7b15b536bf8c7a9
                                 at /home/silveira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:352:34
    19:     0x55dac604f09a - build_script_build::ring_build_rs_main::h2298d5e6524edb11
                                 at /home/silveira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:279:5
    20:     0x55dac604e8cd - build_script_build::main::hcb4196fdf3283bd6
                                 at /home/silveira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:240:13
    21:     0x55dac604cd0b - core::ops::function::FnOnce::call_once::hd15b02c7eab37ab9
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/ops/function.rs:250:5
    22:     0x55dac604c3ee - std::sys_common::backtrace::__rust_begin_short_backtrace::hcff1030303f512f6
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/sys_common/backtrace.rs:154:18
    23:     0x55dac604c641 - std::rt::lang_start::{{closure}}::h7f5b3cb90e888fa9
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/rt.rs:167:18
    24:     0x55dac60e0247 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h1f1b6918a869ec3c
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/core/src/ops/function.rs:284:13
    25:     0x55dac60e0247 - std::panicking::try::do_call::heb9d85f4a283fb38
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:504:40
    26:     0x55dac60e0247 - std::panicking::try::h7ac2a8aaebc8c7bb
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:468:19
    27:     0x55dac60e0247 - std::panic::catch_unwind::h671ff94179299ebf
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panic.rs:142:14
    28:     0x55dac60e0247 - std::rt::lang_start_internal::{{closure}}::h07d605ae212634ca
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/rt.rs:148:48
    29:     0x55dac60e0247 - std::panicking::try::do_call::h7804545faa597905
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:504:40
    30:     0x55dac60e0247 - std::panicking::try::hdf522b3210f130cf
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panicking.rs:468:19
    31:     0x55dac60e0247 - std::panic::catch_unwind::h0b13f1af76b11520
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/panic.rs:142:14
    32:     0x55dac60e0247 - std::rt::lang_start_internal::h3c9d98a55d8fa02b
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/rt.rs:148:20
    33:     0x55dac604c61a - std::rt::lang_start::hbd29d149da853461
                                 at /rustc/0039d739d40a076334e111488946441378d11cd7/library/std/src/rt.rs:166:17
    34:     0x55dac6054fde - main
    35:     0x7f1824629d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    36:     0x7f1824629e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    37:     0x55dac6046d95 - _start
    38:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
```

Cheers,

**Comment by blue-freedom-technologies** [comment]
Closing this issue due the lack of answers from the repository contributors. 

Cheers,

**Comment by briansmith** [comment]
*ring* 0.17 is the first version that has implementations of every algorithm that could work on every target. But, we do have an allowlist of target architectures and target operating systems. I do not know what `riscv32imac-esp-espidf` but it looks like riscv32 which has a good chance of working. The main question is whether the `getrandom` crate supports that target and if not then we probably need PR #1754 to be merged.

**Comment by blue-freedom-technologies** [comment]
Hi,

getrandom supports the target riscv32imac-esp-espidf  with no problem.

```rust
[target.'cfg(all(target_arch = "riscv32imac",target_os = "espidf"))'.dependencies]
getrandom = { git = "https://github.com/rust-random/getrandom.git" }
```

So, does ring have support for  riscv32 ?

**Comment by briansmith** [comment]
> The following warnings were emitted during compilation:
> ```
> warning: ring@0.17.4: cc: error: unrecognized argument in option ‘-mabi=ilp32’
> warning: ring@0.17.4: cc: note: valid arguments to ‘-mabi=’ are: ms sysv
> warning: ring@0.17.4: cc: error: unrecognized argument in option ‘-mcmodel=medany’
> warning: ring@0.17.4: cc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
> ```

You need to set `TARGET_CC` or equivalent to the C compiler for the target. 

See also https://github.com/briansmith/ring/issues/1787 where I describe a bit of what's wrong with `getrandom`'s implementation on this target.

**Comment by blue-freedom-technologies** [comment]
> > The following warnings were emitted during compilation:
> > ```
> > warning: ring@0.17.4: cc: error: unrecognized argument in option ‘-mabi=ilp32’
> > warning: ring@0.17.4: cc: note: valid arguments to ‘-mabi=’ are: ms sysv
> > warning: ring@0.17.4: cc: error: unrecognized argument in option ‘-mcmodel=medany’
> > warning: ring@0.17.4: cc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
> > ```
> 
> You need to set `TARGET_CC` or equivalent to the C compiler for the target.
> 
> See also #1787 where I describe a bit of what's wrong with `getrandom`'s implementation on this target.

I think I am doing something wrong. I have already tried several types of configuration but I am not able to compile the ring.

Do I need some special configuration or flag ?

```bash
TARGET_CC=/opt/riscv/bin/riscv64-unknown-elf-run cargo build --release
```

```text
The following warnings were emitted during compilation:

warning: ring@0.17.5: riscv64-unknown-elf-run: unrecognized option '-O'
warning: ring@0.17.5: Use --help for a complete list of options.

error: failed to run custom build command for `ring v0.17.5`

Caused by:
  process didn't exit successfully: `/home/silveira/bluefreedom/microcontroller/std/prototype-app/target/release/build/ring-e475624193d1286e/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_5_
  OPT_LEVEL = Some("s")
  TARGET = Some("riscv32imac-esp-espidf")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_riscv32imac-esp-espidf
  CC_riscv32imac-esp-espidf = None
  cargo:rerun-if-env-changed=CC_riscv32imac_esp_espidf
  CC_riscv32imac_esp_espidf = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = Some("/opt/riscv/bin/riscv64-unknown-elf-run")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("a,c,m")
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac-esp-espidf
  CFLAGS_riscv32imac-esp-espidf = None
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac_esp_espidf
  CFLAGS_riscv32imac_esp_espidf = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "/opt/riscv/bin/riscv64-unknown-elf-run" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv32imac" "-mabi=ilp32" "-mcmodel=medany" "-I" "include" "-I" "/home/silveira/bluefreedom/microcontroller/std/prototype-app/target/riscv32imac-esp-espidf/release/build/ring-5511d174fa612989/out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-o" "/home/silveira/bluefreedom/microcontroller/std/prototype-app/target/riscv32imac-esp-espidf/release/build/ring-5511d174fa612989/out/crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c"
  cargo:warning=riscv64-unknown-elf-run: unrecognized option '-O'

  cargo:warning=Use --help for a complete list of options.

  exit status: 1

  --- stderr


  error occurred: Command "/opt/riscv/bin/riscv64-unknown-elf-run" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv32imac" "-mabi=ilp32" "-mcmodel=medany" "-I" "include" "-I" "/home/silveira/bluefreedom/microcontroller/std/prototype-app/target/riscv32imac-esp-espidf/release/build/ring-5511d174fa612989/out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-o" "/home/silveira/bluefreedom/microcontroller/std/prototype-app/target/riscv32imac-esp-espidf/release/build/ring-5511d174fa612989/out/crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c" with args "riscv64-unknown-elf-run" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
```

**Comment by blue-freedom-technologies** [comment]
Hi, @briansmith 

Is there any solution for this issue ?

Happy new year, cheers.

**Comment by abergmeier** [comment]
For me it fails due to `riscv32-esp-elf-gcc` not being supported.

**Comment by briansmith** [comment]
Issue #1943 is related to this. PR #1944 is taking a step toward getting this working.

**Comment by briansmith** [comment]
Usually I use Ubuntu, and also *ring*'s CI normally runs on UBuntu. It would accelerate the process of supporting this target if somebody could document how to install the toolchain for this target on Ubuntu so that I can test that the build succeeds, 

Pointers to other projects that support this target that have GitHub Actions working would also be appreciated.

It would be even better if somebody could submit a PR that modifies `mk/{install-build-tools.sh,cargo.sh}` and .github/workflows/ci.yml to add this target to CI, at least so that `cargo.sh test --norun` works.
