### ISSUE TITLE
Build fails on the powerpc64le architecture: thread 'main' panicked at xx called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by yurivict** [briansmith/ring#1904]
```
[ring 0.16.20] thread 'main' panicked at /wrkdirs/usr/ports/net/narrowlink/work/narrowlink-0.2.2/cargo-crates/ring-0.16.20/build.rs:358:10:
[ring 0.16.20] called `Option::unwrap()` on a `None` value
[ring 0.16.20] stack backtrace:
[ring 0.16.20] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `ring v0.16.20`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/wrkdirs/usr/ports/net/narrowlink/work/target/release/build/ring-cce318c300fbdc0b/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /wrkdirs/usr/ports/net/narrowlink/work/narrowlink-0.2.2/cargo-crates/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
*** Error code 101
```

See the log [log](https://pkg-status.freebsd.org/foul2/data/132powerpc64le-quarterly/756e18783d8b/logs/narrowlink-0.2.2.log).

**Comment by briansmith** [comment]
> ring 0.16.20

You need to upgrade to the latest *ring* 0.17.x release.

**Comment by briansmith** [comment]
Specifically, *ring* 0.16.x doesn't support powerpc64. *ring* 0.17 added powerpc support that is even tested in CI.
