### ISSUE TITLE
[question/bug] Problem building for riscv64gc. Are there plans to support it?

### ISSUE THREAD

**Issue by johnnyasantoss** [briansmith/ring#2148]
Hello,

I'm trying to cross compile [floresta](https://github.com/vinteumorg/Floresta) @ 362c0ea to a riscv64gc target and I keep getting this error:

<details><summary>Log</summary>
<p>

```log
[... removed for brevity ...]
   Compiling ring v0.17.8
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/johnny/floresta/target/release/build/ring-ba79b7fef4ca7b16/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/johnny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  stack backtrace:
     0:     0xbfd18c616690 - std::backtrace_rs::backtrace::libunwind::trace::heef1386c69141c0e
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0xbfd18c616690 - std::backtrace_rs::backtrace::trace_unsynchronized::hf52898491dc115b3
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0xbfd18c616690 - std::sys_common::backtrace::_print_fmt::h54a977219eb084db
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
     3:     0xbfd18c616690 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14034993f2dfde80
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
     4:     0xbfd18c638b7c - core::fmt::rt::Argument::fmt::hc7ab06fc179a0538
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
     5:     0xbfd18c638b7c - core::fmt::write::h5c1b4d7dd1fe1297
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
     6:     0xbfd18c612f48 - std::io::Write::write_fmt::h5288162c5e42a3a2
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
     7:     0xbfd18c6164c4 - std::sys_common::backtrace::_print::he08b7cac662e6bf2
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
     8:     0xbfd18c6164c4 - std::sys_common::backtrace::print::hfc02f4f778cfba10
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
     9:     0xbfd18c6180ac - std::panicking::default_hook::{{closure}}::ha5e3ccf8ff24afce
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
    10:     0xbfd18c617dc0 - std::panicking::default_hook::h8515e68938392e65
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
    11:     0xbfd18c618668 - std::panicking::rust_panic_with_hook::hc79d39f29b02a8f2
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
    12:     0xbfd18c6184ec - std::panicking::begin_panic_handler::{{closure}}::hc334b8544d985752
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13
    13:     0xbfd18c616b74 - std::sys_common::backtrace::__rust_end_short_backtrace::h1479ad9e3d67013a
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
    14:     0xbfd18c618288 - rust_begin_unwind
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
    15:     0xbfd18c55fd9c - core::panicking::panic_fmt::h35c6be226eceb7e0
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
    16:     0xbfd18c55fe10 - core::panicking::panic::h8a4c6e356ed191d2
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
    17:     0xbfd18c571eec - core::option::Option<T>::unwrap::h548f6629ba5894a4
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/option.rs:935:21
    18:     0xbfd18c56323c - build_script_build::build_c_code::hac92f018442f181d
                                 at /home/johnny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:352:34
    19:     0xbfd18c562adc - build_script_build::ring_build_rs_main::hc56a4761a93928d7
                                 at /home/johnny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:279:5
    20:     0xbfd18c5624f4 - build_script_build::main::hfe8c1e0bf5a0c8ca
                                 at /home/johnny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:240:13
    21:     0xbfd18c56906c - core::ops::function::FnOnce::call_once::hbe3a123d82360ed9
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
    22:     0xbfd18c5688cc - std::sys_common::backtrace::__rust_begin_short_backtrace::ha93f74b452f933c5
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
    23:     0xbfd18c568958 - std::rt::lang_start::{{closure}}::h0c54c45a09aa5fb8
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:166:18
    24:     0xbfd18c60dba8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf61f7cbe35478064
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
    25:     0xbfd18c60dba8 - std::panicking::try::do_call::he002a9d8b88eec92
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
    26:     0xbfd18c60dba8 - std::panicking::try::h623ba8c426e94cd9
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
    27:     0xbfd18c60dba8 - std::panic::catch_unwind::h145c7caddb5ceae3
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
    28:     0xbfd18c60dba8 - std::rt::lang_start_internal::{{closure}}::h98e3135c0b0dadc6
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
    29:     0xbfd18c60dba8 - std::panicking::try::do_call::hf8fca3c9ffc6d981
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
    30:     0xbfd18c60dba8 - std::panicking::try::h9de3ce8279c045a7
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
    31:     0xbfd18c60dba8 - std::panic::catch_unwind::hc2636d38b3ad5f51
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
    32:     0xbfd18c60dba8 - std::rt::lang_start_internal::he29c91d67ad39838
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
    33:     0xbfd18c568928 - std::rt::lang_start::h6ae177886838b6a3
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:165:17
    34:     0xbfd18c5672dc - main
    35:     0xe129991c84c4 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    36:     0xe129991c8598 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:360:3
    37:     0xbfd18c560330 - _start
    38:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
[... removed for brevity ...]
```

</p>
</details> 

it seems like this architecture isn't well-supported yet.
Are there any plans to support it? Is this fixable? or should I open another issue on the other repo to try avoiding having this dep?
Is riscv64 an arch that you have plans to support?

**Comment by briansmith** [comment]
> ring-0.16.20

riscv64gc is supported in the latest *ring* 0.17.X versions and not in 0.16.x.

**Comment by johnnyasantoss** [comment]
thank you
