### ISSUE TITLE
build fails (0.13.5) with rust nightly 

### ISSUE THREAD

**Issue by brenzi** [briansmith/ring#743]
on ubuntu 18.04 with
```
> rustc +nightly --version
rustc 1.33.0-nightly (a7be40c65 2018-12-26)
```

```
   Compiling ring v0.13.5
error: failed to run custom build command for `ring v0.13.5`
process didn't exit successfully: `/home/brenzi/encointer/encointer-node/runtime/wasm/target/release/build/ring-3c9355820b0022d5/build-script-build` (exit code: 101)
--- stdout
APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: true
CARGO: /home/brenzi/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/cargo
CARGO_CFG_DEBUG_ASSERTIONS:
CARGO_CFG_PROC_MACRO:
CARGO_CFG_TARGET_ARCH: wasm32
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV:
CARGO_CFG_TARGET_HAS_ATOMIC: 16,32,64,8,cas,ptr
CARGO_CFG_TARGET_OS: unknown
CARGO_CFG_TARGET_POINTER_WIDTH: 32
CARGO_CFG_TARGET_VENDOR: unknown
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: /home/brenzi/.cargo
CARGO_INCREMENTAL: 0
CARGO_MAKEFLAGS: --jobserver-fds=3,27 -j --jobserver-auth=3,27 -j
CARGO_MANIFEST_DIR: /home/brenzi/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.5
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE:
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.13.5
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 13
CARGO_PKG_VERSION_PATCH: 5
CARGO_PKG_VERSION_PRE:
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
DEBUG: false
DEFAULTS_PATH: /usr/share/gconf/xfce.default.path
DESKTOP_SESSION: xfce
DISPLAY: :0.0
EDITOR: /bin/nano
GDMSESSION: xfce
GDM_LANG: en_US
GLADE_CATALOG_PATH: :
GLADE_MODULE_PATH: :
GLADE_PIXMAP_PATH: :
GOPATH: /home/brenzi/go
GOROOT: /usr/local/go
GTK2_MODULES: overlay-scrollbar
GTK_CSD: 0
GTK_MODULES: gail:atk-bridge
HOME: /home/brenzi
HOST: i686-unknown-linux-gnu
LANG: en_US.UTF-8
LANGUAGE: en_US
LC_ADDRESS: de_CH.UTF-8
LC_IDENTIFICATION: de_CH.UTF-8
LC_MEASUREMENT: de_CH.UTF-8
LC_MONETARY: de_CH.UTF-8
LC_NAME: de_CH.UTF-8
LC_NUMERIC: de_CH.UTF-8
LC_PAPER: de_CH.UTF-8
LC_TELEPHONE: de_CH.UTF-8
LC_TIME: de_CH.UTF-8
LD_LIBRARY_PATH: /home/brenzi/encointer/encointer-node/runtime/wasm/target/release/deps:/home/brenzi/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib:/home/brenzi/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib
LD_PRELOAD: libgtk3-nocsd.so.0
LESSCLOSE: /usr/bin/lesspipe %s %s
LESSOPEN: | /usr/bin/lesspipe %s
LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:/usr/lib32:/usr/lib/x86_64-linux-gnu:/usr/lib32:
LOGNAME: brenzi
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MANDATORY_PATH: /usr/share/gconf/xfce.mandatory.path
MANPATH: /home/brenzi/.nvm/versions/node/v6.9.2/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
NUM_JOBS: 2
NVM_BIN: /home/brenzi/.nvm/versions/node/v6.9.2/bin
NVM_CD_FLAGS:
NVM_DIR: /home/brenzi/.nvm
NVM_IOJS_ORG_MIRROR: https://iojs.org/dist
NVM_NODEJS_ORG_MIRROR: https://nodejs.org/dist
NVM_PATH: /home/brenzi/.nvm/versions/node/v6.9.2/lib/node
OLDPWD: /home/brenzi/encointer/encointer-node
OPT_LEVEL: 3
OUT_DIR: /home/brenzi/encointer/encointer-node/runtime/wasm/target/wasm32-unknown-unknown/release/build/ring-7839695bc0bb8e42/out
PAM_KWALLET5_LOGIN: /run/user/1000/kwallet5.socket
PAM_KWALLET_LOGIN: /run/user/1000/kwallet.socket
PATH: /home/brenzi/.cargo/bin:/home/brenzi/.nvm/versions/node/v6.9.2/bin:/home/brenzi/go/bin:/home/brenzi/go/bin:/usr/local/go/bin:/home/brenzi/.cargo/bin:/home/brenzi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/mnt/data2/android-sdk-linux/tools:/mnt/data2/android-sdk-linux/platform-tools::/mnt/data2/android-sdk-linux/tools:/mnt/data2/android-sdk-linux/platform-tools:
PROFILE: release
PWD: /home/brenzi/encointer/encointer-node/runtime/wasm
QT_ACCESSIBILITY: 1
QT_QPA_PLATFORMTHEME: appmenu-qt5
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: /home/brenzi/.rustup
RUSTUP_TOOLCHAIN: nightly-i686-unknown-linux-gnu
RUST_BACKTRACE: full
RUST_RECURSION_COUNT: 1
SESSION_MANAGER: local/blackbox:@/tmp/.ICE-unix/3808,unix/blackbox:/tmp/.ICE-unix/3808
SGX_MODE: SIM
SGX_SSL: /opt/intel/sgxssl
SHELL: /bin/bash
SHLVL: 5
SNAP: /snap/vscode/72
SNAP_ARCH: amd64
SNAP_COMMON: /var/snap/vscode/common
SNAP_CONTEXT: KSHdf95hMMlPkl5txg1670flPY6Y8lKRJFYwSRSJ3JR8
SNAP_COOKIE: KSHdf95hMMlPkl5txg1670flPY6Y8lKRJFYwSRSJ3JR8
SNAP_DATA: /var/snap/vscode/72
SNAP_INSTANCE_KEY:
SNAP_INSTANCE_NAME: vscode
SNAP_LIBRARY_PATH: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
SNAP_NAME: vscode
SNAP_REEXEC:
SNAP_REVISION: 72
SNAP_USER_COMMON: /home/brenzi/snap/vscode/common
SNAP_USER_DATA: /home/brenzi/snap/vscode/72
SNAP_VERSION: 1.30.0-1544567151
SSH_AGENT_PID: 3790
SSH_AUTH_SOCK: /tmp/ssh-kQBFXUbUG1vd/agent.3696
SSL_CERT_DIR: /usr/local/ssl/certs
SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
TARGET: wasm32-unknown-unknown
TERM: xterm-256color
TERM_PROGRAM: vscode
TERM_PROGRAM_VERSION: 1.30.0
TINY_SCHEME_SRC: /home/brenzi/encointer/testnet/tinyscheme-1.41
USER: brenzi
VIRTUALENVWRAPPER_HOOK_DIR: /home/brenzi/.virtualenvs
VIRTUALENVWRAPPER_PROJECT_FILENAME: .project
VIRTUALENVWRAPPER_SCRIPT: /usr/local/bin/virtualenvwrapper.sh
VIRTUALENVWRAPPER_WORKON_CD: 1
WORKON_HOME: /home/brenzi/.virtualenvs
XAUTHORITY: /home/brenzi/.Xauthority
XDG_CONFIG_DIRS: /etc/xdg/xdg-xfce:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings:/etc/xdg
XDG_CURRENT_DESKTOP: XFCE
XDG_DATA_DIRS: /usr/share/xfce4:/usr/share/xfce:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop:/usr/share
XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/brenzi
XDG_MENU_PREFIX: xfce-
XDG_RUNTIME_DIR: /run/user/1000/snap.vscode
XDG_SEAT: seat0
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_DESKTOP: xfce
XDG_SESSION_ID: c2
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE: x11
XDG_VTNR: 7
_: /home/brenzi/.cargo/bin/cargo

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: 0x5665333c - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1d2d6fdafb9f3cdb
                       at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: 0x5664f49b - std::sys_common::backtrace::_print::he0fb19662ddbb9ae
                       at src/libstd/sys_common/backtrace.rs:70
   2: 0x56651fe2 - std::panicking::default_hook::{{closure}}::hf279fe322dcb0ed0
                       at src/libstd/sys_common/backtrace.rs:58
                       at src/libstd/panicking.rs:200
   3: 0x56651d11 - std::panicking::default_hook::h0ffaf53f67b8a189
                       at src/libstd/panicking.rs:215
   4: 0x5665277c - std::panicking::rust_panic_with_hook::h86e91f8bd222a39b
                       at src/libstd/panicking.rs:478
   5: 0x566522b6 - std::panicking::continue_panic_fmt::h1d1263d0afb6a132
                       at src/libstd/panicking.rs:385
   6: 0x56652188 - rust_begin_unwind
                       at src/libstd/panicking.rs:312
   7: 0x5666a0f9 - core::panicking::panic_fmt::hc95d794825ab2d63
                       at src/libcore/panicking.rs:85
   8: 0x5666a00b - core::panicking::panic::hfbd111605b190ca6
                       at src/libcore/panicking.rs:49
   9: 0x5661d7af - build_script_build::main::h8fe4bd54bf9eb022
  10: 0x56620aa5 - std::rt::lang_start::{{closure}}::hcd291d745b89bcd1
  11: 0x56650485 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd3860c06444b7d8b
                       at src/libstd/rt.rs:49
                       at src/libstd/sys_common/backtrace.rs:135
  12: 0x566520fe - std::panicking::try::do_call::h8204a3f515807d2d
                       at src/libstd/rt.rs:49
                       at src/libstd/panicking.rs:297
  13: 0x5665a357 - __rust_maybe_catch_panic
                       at src/libpanic_unwind/lib.rs:92
  14: 0x56652c2f - std::rt::lang_start_internal::h0fc368d9a413a58d
                       at src/libstd/panicking.rs:276
                       at src/libstd/panic.rs:388
                       at src/libstd/rt.rs:48
  15: 0x56620a40 - main
  16: 0xf7cc3e80 - __libc_start_main
  17: 0x56619760 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by briansmith** [comment]
That build has target `wasm32-unknown-unknown` which of course doesn't work. Are you really targetting that target or is that an accident?

**Comment by brenzi** [comment]
my bad, sorry. please close

**Comment by briansmith** [comment]
Thanks for following up!

**Comment by briansmith** [comment]
wasm32-unknown-unknown support will be tracked in #803 657.
