### ISSUE TITLE
Build fail on debian wheezy

### ISSUE THREAD

**Issue by nappa85** [briansmith/ring#823]
The crate fails to build on a debian wheezy environment.
I know this distro is discontinued, but I actually need to build on it.
I know it's some outdated or missing dependency, but I'm unable to debug it.
This is the build output:

> #15 29.34 error: failed to run custom build command for `ring v0.14.6`
> #15 29.34 process didn't exit successfully: `/usr/src/terminus/target/release/build/ring-e570674ba4e800b6/build-script-build` (exit code: 101)
> #15 29.34 --- stdout
> #15 29.34 CARGO: /usr/local/rustup/toolchains/1.34.2-x86_64-unknown-linux-gnu/bin/cargo
> #15 29.34 CARGO_CFG_DEBUG_ASSERTIONS: 
> #15 29.34 CARGO_CFG_PROC_MACRO: 
> #15 29.34 CARGO_CFG_TARGET_ARCH: x86_64
> #15 29.34 CARGO_CFG_TARGET_ENDIAN: little
> #15 29.34 CARGO_CFG_TARGET_ENV: gnu
> #15 29.34 CARGO_CFG_TARGET_FAMILY: unix
> #15 29.34 CARGO_CFG_TARGET_FEATURE: fxsr,sse,sse2
> #15 29.34 CARGO_CFG_TARGET_OS: linux
> #15 29.34 CARGO_CFG_TARGET_POINTER_WIDTH: 64
> #15 29.34 CARGO_CFG_TARGET_VENDOR: unknown
> #15 29.34 CARGO_CFG_UNIX: 
> #15 29.34 CARGO_FEATURE_DEFAULT: 1
> #15 29.34 CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
> #15 29.34 CARGO_FEATURE_USE_HEAP: 1
> #15 29.34 CARGO_HOME: /usr/local/cargo
> #15 29.34 CARGO_MAKEFLAGS: --jobserver-fds=4,8 -j --jobserver-auth=4,8 -j
> #15 29.34 CARGO_MANIFEST_DIR: /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6
> #15 29.34 CARGO_MANIFEST_LINKS: ring-asm
> #15 29.34 CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
> #15 29.34 CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
> #15 29.34 CARGO_PKG_HOMEPAGE: 
> #15 29.34 CARGO_PKG_NAME: ring
> #15 29.34 CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
> #15 29.34 CARGO_PKG_VERSION: 0.14.6
> #15 29.34 CARGO_PKG_VERSION_MAJOR: 0
> #15 29.34 CARGO_PKG_VERSION_MINOR: 14
> #15 29.34 CARGO_PKG_VERSION_PATCH: 6
> #15 29.34 CARGO_PKG_VERSION_PRE: 
> #15 29.34 DEBUG: false
> #15 29.34 HOME: /root
> #15 29.34 HOST: x86_64-unknown-linux-gnu
> #15 29.34 LD_LIBRARY_PATH: /usr/src/terminus/target/release/deps:/usr/local/rustup/toolchains/1.34.2-x86_64-unknown-linux-gnu/lib:/usr/local/rustup/toolchains/1.34.2-x86_64-unknown-linux-gnu/lib
> #15 29.34 NOTIFY_SOCKET: /run/systemd/notify
> #15 29.34 NUM_JOBS: 16
> #15 29.34 OPT_LEVEL: 3
> #15 29.34 OUT_DIR: /usr/src/terminus/target/release/build/ring-3c5a9c9eea058122/out
> #15 29.34 PATH: /usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> #15 29.34 PROFILE: release
> #15 29.34 PWD: /usr/src/terminus
> #15 29.34 RUSTC: rustc
> #15 29.34 RUSTDOC: rustdoc
> #15 29.34 RUSTUP_HOME: /usr/local/rustup
> #15 29.34 RUSTUP_TOOLCHAIN: 1.34.2-x86_64-unknown-linux-gnu
> #15 29.34 RUST_BACKTRACE: 1
> #15 29.34 RUST_RECURSION_COUNT: 1
> #15 29.34 RUST_VERSION: 1.34.2
> #15 29.34 SSH_AUTH_SOCK: /run/buildkit/ssh_agent.0
> #15 29.34 SSL_CERT_DIR: /usr/lib/ssl/certs
> #15 29.34 SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
> #15 29.34 TARGET: x86_64-unknown-linux-gnu
> #15 29.34 OPT_LEVEL = Some("3")
> #15 29.34 TARGET = Some("x86_64-unknown-linux-gnu")
> #15 29.34 HOST = Some("x86_64-unknown-linux-gnu")
> #15 29.34 CC_x86_64-unknown-linux-gnu = None
> #15 29.34 CC_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CC = None
> #15 29.34 CC = None
> #15 29.34 CFLAGS_x86_64-unknown-linux-gnu = None
> #15 29.34 CFLAGS_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CFLAGS = None
> #15 29.34 CFLAGS = None
> #15 29.34 CRATE_CC_NO_DEFAULTS = None
> #15 29.34 DEBUG = Some("false")
> #15 29.34 CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
> #15 29.34 running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-D_XOPEN_SOURCE=700" "-c" "-o/usr/src/terminus/target/release/build/ring-3c5a9c9eea058122/out/aes-x86_64-elf.o" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/aes-x86_64-elf.S"
> #15 29.34 OPT_LEVEL = Some("3")
> #15 29.34 TARGET = Some("x86_64-unknown-linux-gnu")
> #15 29.34 HOST = Some("x86_64-unknown-linux-gnu")
> #15 29.34 CC_x86_64-unknown-linux-gnu = None
> #15 29.34 CC_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CC = None
> #15 29.34 CC = None
> #15 29.34 CFLAGS_x86_64-unknown-linux-gnu = None
> #15 29.34 CFLAGS_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CFLAGS = None
> #15 29.34 CFLAGS = None
> #15 29.34 CRATE_CC_NO_DEFAULTS = None
> #15 29.34 DEBUG = Some("false")
> #15 29.34 CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
> #15 29.34 running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-D_XOPEN_SOURCE=700" "-c" "-o/usr/src/terminus/target/release/build/ring-3c5a9c9eea058122/out/aesni-x86_64-elf.o" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/aesni-x86_64-elf.S"
> #15 29.34 OPT_LEVEL = Some("3")
> #15 29.34 TARGET = Some("x86_64-unknown-linux-gnu")
> #15 29.34 HOST = Some("x86_64-unknown-linux-gnu")
> #15 29.34 CC_x86_64-unknown-linux-gnu = None
> #15 29.34 CC_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CC = None
> #15 29.34 CC = None
> #15 29.34 CFLAGS_x86_64-unknown-linux-gnu = None
> #15 29.34 CFLAGS_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CFLAGS = None
> #15 29.34 CFLAGS = None
> #15 29.34 CRATE_CC_NO_DEFAULTS = None
> #15 29.34 DEBUG = Some("false")
> #15 29.34 CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
> #15 29.34 running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-D_XOPEN_SOURCE=700" "-c" "-o/usr/src/terminus/target/release/build/ring-3c5a9c9eea058122/out/vpaes-x86_64-elf.o" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/vpaes-x86_64-elf.S"
> #15 29.34 OPT_LEVEL = Some("3")
> #15 29.34 TARGET = Some("x86_64-unknown-linux-gnu")
> #15 29.34 HOST = Some("x86_64-unknown-linux-gnu")
> #15 29.34 CC_x86_64-unknown-linux-gnu = None
> #15 29.34 CC_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CC = None
> #15 29.34 CC = None
> #15 29.34 CFLAGS_x86_64-unknown-linux-gnu = None
> #15 29.34 CFLAGS_x86_64_unknown_linux_gnu = None
> #15 29.34 HOST_CFLAGS = None
> #15 29.34 CFLAGS = None
> #15 29.34 CRATE_CC_NO_DEFAULTS = None
> #15 29.34 DEBUG = Some("false")
> #15 29.34 CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
> #15 29.34 running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-D_XOPEN_SOURCE=700" "-c" "-o/usr/src/terminus/target/release/build/ring-3c5a9c9eea058122/out/x86_64-mont-elf.o" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S"
> #15 29.34 
> #15 29.34 --- stderr
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S: Assembler messages:
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:986: Error: no such instruction: `adcxq %rax,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:987: Error: no such instruction: `adcxq %rbp,%r14'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:990: Error: no such instruction: `adcxq %rax,%rdi'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:991: Error: no such instruction: `adoxq %r11,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:993: Error: no such instruction: `adcxq %rax,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:994: Error: no such instruction: `adoxq %r12,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:998: Error: no such instruction: `adcxq %rax,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:999: Error: no such instruction: `adoxq %r13,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1003: Error: no such instruction: `adcxq %rax,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1004: Error: no such instruction: `adoxq %rbp,%r15'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1012: Error: no such instruction: `adcxq %rbp,%r15'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1014: Error: no such instruction: `adcxq %r14,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1016: Error: no such instruction: `adcxq %rax,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1018: Error: no such instruction: `adcxq %r14,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1022: Error: no such instruction: `adcxq %rax,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1023: Error: no such instruction: `adcxq %rbp,%r14'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1027: Error: no such instruction: `adoxq %r15,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1029: Error: no such instruction: `adcxq %rax,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1030: Error: no such instruction: `adoxq %r15,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1032: Error: no such instruction: `adcxq %rax,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1033: Error: no such instruction: `adoxq %r15,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1036: Error: no such instruction: `adcxq %rax,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1038: Error: no such instruction: `adoxq %r15,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1042: Error: no such instruction: `adcxq %rax,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1043: Error: no such instruction: `adoxq %rbp,%r15'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1071: Error: no such instruction: `adoxq -32(%rbx),%r8'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1072: Error: no such instruction: `adcxq %r14,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1074: Error: no such instruction: `adoxq -24(%rbx),%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1075: Error: no such instruction: `adcxq %r15,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1076: Error: no such instruction: `adoxq -16(%rbx),%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1077: Error: no such instruction: `adcxq %rbp,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1078: Error: no such instruction: `adoxq %rbp,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1087: Error: no such instruction: `adcxq %rax,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1088: Error: no such instruction: `adoxq -8(%rbx),%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1089: Error: no such instruction: `adcxq %rbp,%r14'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1091: Error: no such instruction: `adoxq %rbp,%r14'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1094: Error: no such instruction: `adcxq %rax,%r15'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1095: Error: no such instruction: `adoxq %r11,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1097: Error: no such instruction: `adcxq %rax,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1098: Error: no such instruction: `adoxq %r12,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1101: Error: no such instruction: `adcxq %rax,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1102: Error: no such instruction: `adoxq %r13,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1107: Error: no such instruction: `adcxq %rax,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1108: Error: no such instruction: `adoxq %rbp,%r15'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1117: Error: no such instruction: `adcxq %rbp,%r15'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1118: Error: no such instruction: `adoxq %r14,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1120: Error: no such instruction: `adcxq 0(%rbx),%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1121: Error: no such instruction: `adoxq %rax,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1123: Error: no such instruction: `adcxq 8(%rbx),%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1124: Error: no such instruction: `adoxq %r14,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1127: Error: no such instruction: `adcxq 16(%rbx),%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1128: Error: no such instruction: `adoxq %rax,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1129: Error: no such instruction: `adcxq 24(%rbx),%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1130: Error: no such instruction: `adoxq %rbp,%r14'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1133: Error: no such instruction: `adcxq %rbp,%r14'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1135: Error: no such instruction: `adoxq %r15,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1137: Error: no such instruction: `adcxq %rax,%r10'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1138: Error: no such instruction: `adoxq %r15,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1140: Error: no such instruction: `adcxq %rax,%r11'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1141: Error: no such instruction: `adoxq %r15,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1144: Error: no such instruction: `adcxq %rax,%r12'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1145: Error: no such instruction: `adoxq %r15,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1150: Error: no such instruction: `adcxq %rax,%r13'
> #15 29.34 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/pregenerated/x86_64-mont-elf.S:1151: Error: no such instruction: `adoxq %rbp,%r15'
> #15 29.34 thread 'main' panicked at 'execution failed', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/build.rs:638:9
> #15 29.34 stack backtrace:
> #15 29.34    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
> #15 29.34              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
> #15 29.34    1: std::sys_common::backtrace::_print
> #15 29.34              at src/libstd/sys_common/backtrace.rs:70
> #15 29.34    2: std::panicking::default_hook::{{closure}}
> #15 29.34              at src/libstd/sys_common/backtrace.rs:58
> #15 29.34              at src/libstd/panicking.rs:200
> #15 29.34    3: std::panicking::default_hook
> #15 29.34              at src/libstd/panicking.rs:215
> #15 29.34    4: std::panicking::rust_panic_with_hook
> #15 29.34              at src/libstd/panicking.rs:478
> #15 29.34    5: std::panicking::begin_panic
> #15 29.34    6: build_script_build::run_command
> #15 29.34    7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
> #15 29.34    8: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::next
> #15 29.34    9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
> #15 29.34   10: build_script_build::main
> #15 29.34   11: std::rt::lang_start::{{closure}}
> #15 29.34   12: std::panicking::try::do_call
> #15 29.34              at src/libstd/rt.rs:49
> #15 29.34              at src/libstd/panicking.rs:297
> #15 29.34   13: __rust_maybe_catch_panic
> #15 29.34              at src/libpanic_unwind/lib.rs:87
> #15 29.34   14: std::rt::lang_start_internal
> #15 29.34              at src/libstd/panicking.rs:276
> #15 29.34              at src/libstd/panic.rs:388
> #15 29.34              at src/libstd/rt.rs:48
> #15 29.34   15: main
> #15 29.34   16: __libc_start_main
> #15 29.34   17: <unknown>
> #15 29.34 
> #15 29.34 warning: build failed, waiting for other jobs to finish...

Which are the build deps I have to check?
Thank you

**Comment by nappa85** [comment]
Nevermind, found solution on issue #689
